/*
 * Setor XI — dados do catálogo
 * ------------------------------------------------------------------
 * Edite APENAS este arquivo para mudar os produtos da vitrine.
 * O restante (app.js / styles.css) não precisa ser tocado.
 *
 * Campos de cada produto:
 *   id        string   identificador único (sem espaços)
 *   name      string   nome da camisa
 *   category  string   categoria — os filtros são gerados a partir daqui
 *   price     number   preço em reais, ex.: 170  (não use "R$" nem vírgula)
 *             null     use null para exibir "Entrar em contato"
 *   number    string   número exibido no placeholder da marca (opcional)
 *   image     string   caminho da foto real, ex.: "fotos/belgica.jpg"
 *                       deixe null para usar o placeholder gerado pela marca
 *   badge     string   selo opcional no card, ex.: "Novo" (use null se não quiser)
 * ------------------------------------------------------------------
 */
window.SETOR_XI_PRODUCTS = [
  {
    id: "selecao-alemanha-casa",
    name: "Alemanha 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/alemanha-casa.jpg",
    badge: null,
  },
  {
    id: "selecao-alemanha-fora",
    name: "Alemanha 2026/27 — Fora",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/alemanha-fora.jpg",
    badge: null,
  },
  {
    id: "selecao-argentina-casa",
    name: "Argentina 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/argentina-casa.jpg",
    badge: null,
  },
  {
    id: "selecao-argentina-fora",
    name: "Argentina 2026/27 — Fora",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/argentina-fora.jpg",
    badge: null,
  },
  {
    id: "selecao-belgica",
    name: "Bélgica 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/belgica.jpg",
    badge: null,
  },
  {
    id: "selecao-brasil-manga-longa",
    name: "Brasil 2026/27 — Manga Longa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/brasil-manga-longa.jpg",
    badge: null,
  },
  {
    id: "selecao-cabo-verde",
    name: "Cabo Verde 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/cabo-verde.jpg",
    badge: null,
  },
  {
    id: "selecao-espanha-casa",
    name: "Espanha 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/espanha-casa.jpg",
    badge: null,
  },
  {
    id: "selecao-espanha-fora",
    name: "Espanha 2026/27 — Fora",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/espanha-fora.jpg",
    badge: null,
  },
  {
    id: "selecao-franca-casa",
    name: "França 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/franca-casa.jpg",
    badge: null,
  },
  {
    id: "selecao-franca-fora",
    name: "França 2026/27 — Fora",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/franca-fora.jpg",
    badge: null,
  },
  {
    id: "clube-i",
    name: "Camisa de Clube I",
    category: "Camisas de Clube",
    price: 170,
    number: "8",
    image: null,
    badge: null,
  },
  {
    id: "clube-ii",
    name: "Camisa de Clube II",
    category: "Camisas de Clube",
    price: 170,
    number: "4",
    image: null,
    badge: null,
  },
  {
    id: "especial-pais-de-gales-150",
    name: "País de Gales — Edição 150 Anos",
    category: "Edições Especiais",
    price: null,
    image: "fotos/pais-de-gales-150-anos.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-newcastle-2004-06",
    name: "Newcastle 2004/06 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/newcastle-2004-06.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-milan-25-26",
    name: "Milan 2025/26 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/milan-25-26.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-liverpool-26-27",
    name: "Liverpool 2026/27 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/liverpool-26-27.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-espanha-26-27",
    name: "Espanha 2026/27 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/espanha-26-27-especial.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-barcelona-26-27",
    name: "Barcelona 2026/27 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/barcelona-26-27.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-barcelona-travis-scott",
    name: "Barcelona 2024/25 — Travis Scott",
    category: "Edições Especiais",
    price: null,
    image: "fotos/barcelona-24-25-travis-scott.jpg",
    badge: "Edição limitada",
  },
  {
    id: "especial-alemanha-26-27",
    name: "Alemanha 2026/27 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/alemanha-26-27-especial.jpg",
    badge: "Edição especial",
  },
  {
    id: "retro-barcelona-centenario",
    name: "Barcelona — Centenário 1899/1999",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-barcelona-centenario.jpg",
    badge: null,
  },
  {
    id: "retro-real-madrid-2017-18-casa",
    name: "Real Madrid 2017/18 — Casa",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-real-madrid-2017-18-casa.jpg",
    badge: null,
  },
  {
    id: "retro-real-madrid-2017-18-terceira",
    name: "Real Madrid 2017/18 — Terceira",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-real-madrid-2017-18-terceira.jpg",
    badge: null,
  },
  {
    id: "retro-milan-2006-07",
    name: "Milan 2006/07 — Fora",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-milan-2006-07.jpg",
    badge: null,
  },
  {
    id: "retro-inter-1998-99",
    name: "Inter de Milão 1998/99",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-inter-1998-99.jpg",
    badge: null,
  },
  {
    id: "retro-roma-2000-01",
    name: "Roma 2000/01 — Fora",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-roma-2000-01.jpg",
    badge: null,
  },
  {
    id: "retro-gremio-anos-90",
    name: "Grêmio — Anos 90",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-gremio-anos-90.jpg",
    badge: null,
  },
  {
    id: "retro-japao-2006",
    name: "Japão 2006",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-japao-2006.jpg",
    badge: null,
  },
];
