/*
 * Setor XI — dados do catálogo
 * ------------------------------------------------------------------
 * Edite APENAS este arquivo para mudar os produtos da vitrine.
 * O restante (app.js / styles.css) não precisa ser tocado.
 *
 * Campos de cada produto:
 *   id        string   identificador único (sem espaços)
 *   name      string   nome da camisa
 *   category  string   categoria — os filtros são gerados a partir daqui
 *   price     number   preço em reais, ex.: 170  (não use "R$" nem vírgula)
 *             null     use null para exibir "Entrar em contato"
 *   number    string   número exibido no placeholder da marca (opcional)
 *   image     string   caminho da foto real, ex.: "fotos/belgica.jpg"
 *                       deixe null para usar o placeholder gerado pela marca
 *   badge     string   selo opcional no card, ex.: "Novo" (use null se não quiser)
 * ------------------------------------------------------------------
 */
window.SETOR_XI_PRODUCTS = [
  {
    id: "selecao-alemanha-casa",
    name: "Alemanha 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/alemanha-casa.jpg",
    badge: null,
  },
  {
    id: "selecao-alemanha-fora",
    name: "Alemanha 2026/27 — Fora",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/alemanha-fora.jpg",
    badge: null,
  },
  {
    id: "selecao-argentina-casa",
    name: "Argentina 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/argentina-casa.jpg",
    badge: null,
  },
  {
    id: "selecao-argentina-fora",
    name: "Argentina 2026/27 — Fora",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/argentina-fora.jpg",
    badge: null,
  },
  {
    id: "selecao-belgica",
    name: "Bélgica 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/belgica.jpg",
    badge: null,
  },
  {
    id: "selecao-brasil-manga-longa",
    name: "Brasil 2026/27 — Manga Longa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/brasil-manga-longa.jpg",
    badge: null,
  },
  {
    id: "selecao-cabo-verde",
    name: "Cabo Verde 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/cabo-verde.jpg",
    badge: null,
  },
  {
    id: "selecao-espanha-casa",
    name: "Espanha 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/espanha-casa.jpg",
    badge: null,
  },
  {
    id: "selecao-espanha-fora",
    name: "Espanha 2026/27 — Fora",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/espanha-fora.jpg",
    badge: null,
  },
  {
    id: "selecao-franca-casa",
    name: "França 2026/27 — Casa",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/franca-casa.jpg",
    badge: null,
  },
  {
    id: "selecao-franca-fora",
    name: "França 2026/27 — Fora",
    category: "Camisas de Seleção",
    price: 170,
    image: "fotos/franca-fora.jpg",
    badge: null,
  },
  {
    id: "clube-corinthians-casa",
    name: "Corinthians 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-corinthians-casa.jpg",
    badge: null,
  },
  {
    id: "clube-corinthians-fora",
    name: "Corinthians 2026/27 — Fora",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-corinthians-fora.jpg",
    badge: null,
  },
  {
    id: "clube-cruzeiro-casa",
    name: "Cruzeiro 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-cruzeiro-casa.jpg",
    badge: null,
  },
  {
    id: "clube-cruzeiro-fora",
    name: "Cruzeiro 2026/27 — Fora",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-cruzeiro-fora.jpg",
    badge: null,
  },
  {
    id: "clube-flamengo-casa",
    name: "Flamengo 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-flamengo-casa.jpg",
    badge: null,
  },
  {
    id: "clube-flamengo-fora",
    name: "Flamengo 2026/27 — Fora",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-flamengo-fora.jpg",
    badge: null,
  },
  {
    id: "clube-gremio-casa",
    name: "Grêmio 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-gremio-casa.jpg",
    badge: null,
  },
  {
    id: "clube-gremio-fora",
    name: "Grêmio 2026/27 — Fora",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-gremio-fora.jpg",
    badge: null,
  },
  {
    id: "clube-palmeiras-casa",
    name: "Palmeiras 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-palmeiras-casa.jpg",
    badge: null,
  },
  {
    id: "clube-palmeiras-fora",
    name: "Palmeiras 2026/27 — Fora",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-palmeiras-fora.jpg",
    badge: null,
  },
  {
    id: "clube-santos-casa",
    name: "Santos 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-santos-casa.jpg",
    badge: null,
  },
  {
    id: "clube-santos-fora",
    name: "Santos 2026/27 — Fora",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-santos-fora.jpg",
    badge: null,
  },
  {
    id: "clube-sao-paulo-casa",
    name: "São Paulo 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-sao-paulo-casa.jpg",
    badge: null,
  },
  {
    id: "clube-sao-paulo-fora",
    name: "São Paulo 2026/27 — Fora",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-sao-paulo-fora.jpg",
    badge: null,
  },
  {
    id: "clube-vasco-casa",
    name: "Vasco 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-vasco-casa.jpg",
    badge: null,
  },
  {
    id: "clube-vasco-fora",
    name: "Vasco 2026/27 — Fora",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-vasco-fora.jpg",
    badge: null,
  },
  {
    id: "clube-arsenal-terceira",
    name: "Arsenal 2026/27 — Terceira",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-arsenal-terceira.jpg",
    badge: null,
  },
  {
    id: "clube-aston-villa-casa",
    name: "Aston Villa 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-aston-villa-casa.jpg",
    badge: null,
  },
  {
    id: "clube-barcelona-casa",
    name: "Barcelona 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-barcelona-casa.jpg",
    badge: null,
  },
  {
    id: "clube-chelsea-casa",
    name: "Chelsea 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-chelsea-casa.jpg",
    badge: null,
  },
  {
    id: "clube-inter-milao-casa",
    name: "Inter de Milão 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-inter-milao-casa.jpg",
    badge: null,
  },
  {
    id: "clube-kawasaki-frontale-casa",
    name: "Kawasaki Frontale 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-kawasaki-frontale-casa.jpg",
    badge: null,
  },
  {
    id: "clube-manchester-united-terceira",
    name: "Manchester United 2026/27 — Terceira",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-manchester-united-terceira.jpg",
    badge: null,
  },
  {
    id: "clube-napoli-casa",
    name: "Napoli 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-napoli-casa.jpg",
    badge: null,
  },
  {
    id: "clube-napoli-fora",
    name: "Napoli 2026/27 — Fora",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-napoli-fora.jpg",
    badge: null,
  },
  {
    id: "clube-psg-casa",
    name: "PSG 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-psg-casa.jpg",
    badge: null,
  },
  {
    id: "clube-real-madrid-casa",
    name: "Real Madrid 2026/27 — Casa",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-real-madrid-casa.jpg",
    badge: null,
  },
  {
    id: "clube-real-madrid-fora",
    name: "Real Madrid 2026/27 — Fora",
    category: "Camisas de Clube",
    price: 170,
    image: "fotos/clube-real-madrid-fora.jpg",
    badge: null,
  },
  {
    id: "especial-pais-de-gales-150",
    name: "País de Gales — Edição 150 Anos",
    category: "Edições Especiais",
    price: null,
    image: "fotos/pais-de-gales-150-anos.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-newcastle-2004-06",
    name: "Newcastle 2004/06 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/newcastle-2004-06.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-milan-25-26",
    name: "Milan 2025/26 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/milan-25-26.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-liverpool-26-27",
    name: "Liverpool 2026/27 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/liverpool-26-27.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-espanha-26-27",
    name: "Espanha 2026/27 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/espanha-26-27-especial.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-barcelona-26-27",
    name: "Barcelona 2026/27 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/barcelona-26-27.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-barcelona-travis-scott",
    name: "Barcelona 2024/25 — Travis Scott",
    category: "Edições Especiais",
    price: null,
    image: "fotos/barcelona-24-25-travis-scott.jpg",
    badge: "Edição limitada",
  },
  {
    id: "especial-alemanha-26-27",
    name: "Alemanha 2026/27 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/alemanha-26-27-especial.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-ajax-25-26",
    name: "Ajax 2025/26 — Edição Comemorativa",
    category: "Edições Especiais",
    price: null,
    image: "fotos/especial-ajax-25-26.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-argentina-2024",
    name: "Argentina 2024 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/especial-argentina-2024.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-barcelona-125-anos",
    name: "Barcelona — 125 Anos",
    category: "Edições Especiais",
    price: null,
    image: "fotos/especial-barcelona-125-anos.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-barcelona-25-26",
    name: "Barcelona 2025/26 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/especial-barcelona-25-26.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-espanha-grena",
    name: "Espanha — Edição Especial Grená",
    category: "Edições Especiais",
    price: null,
    image: "fotos/especial-espanha-grena.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-inter-miami-24-25",
    name: "Inter Miami 2024/25 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/especial-inter-miami-24-25.jpg",
    badge: "Edição especial",
  },
  {
    id: "especial-japao-2024-ace",
    name: "Japão 2024 — Edição Especial (Ace)",
    category: "Edições Especiais",
    price: null,
    image: "fotos/especial-japao-2024-ace.jpg",
    badge: "Edição limitada",
  },
  {
    id: "especial-vasco-25-26",
    name: "Vasco 2025/26 — Edição Especial",
    category: "Edições Especiais",
    price: null,
    image: "fotos/especial-vasco-25-26.jpg",
    badge: "Edição especial",
  },
  {
    id: "retro-barcelona-centenario",
    name: "Barcelona — Centenário 1899/1999",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-barcelona-centenario.jpg",
    badge: null,
  },
  {
    id: "retro-real-madrid-2017-18-casa",
    name: "Real Madrid 2017/18 — Casa",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-real-madrid-2017-18-casa.jpg",
    badge: null,
  },
  {
    id: "retro-real-madrid-2017-18-terceira",
    name: "Real Madrid 2017/18 — Terceira",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-real-madrid-2017-18-terceira.jpg",
    badge: null,
  },
  {
    id: "retro-milan-2006-07",
    name: "Milan 2006/07 — Fora",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-milan-2006-07.jpg",
    badge: null,
  },
  {
    id: "retro-inter-1998-99",
    name: "Inter de Milão 1998/99",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-inter-1998-99.jpg",
    badge: null,
  },
  {
    id: "retro-roma-2000-01",
    name: "Roma 2000/01 — Fora",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-roma-2000-01.jpg",
    badge: null,
  },
  {
    id: "retro-gremio-anos-90",
    name: "Grêmio — Anos 90",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-gremio-anos-90.jpg",
    badge: null,
  },
  {
    id: "retro-japao-2006",
    name: "Japão 2006",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-japao-2006.jpg",
    badge: null,
  },
  {
    id: "retro-ajax-95-96",
    name: "Ajax 1995/96",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-ajax-95-96.jpg",
    badge: null,
  },
  {
    id: "retro-alemanha-1990",
    name: "Alemanha 1990",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-alemanha-1990.jpg",
    badge: null,
  },
  {
    id: "retro-alemanha-2014-casa",
    name: "Alemanha 2014 — Casa",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-alemanha-2014-casa.jpg",
    badge: null,
  },
  {
    id: "retro-alemanha-2014-fora",
    name: "Alemanha 2014 — Fora",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-alemanha-2014-fora.jpg",
    badge: null,
  },
  {
    id: "retro-argentina-00-01",
    name: "Argentina 2000/01",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-argentina-00-01.jpg",
    badge: null,
  },
  {
    id: "retro-argentina-2006",
    name: "Argentina 2006",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-argentina-2006.jpg",
    badge: null,
  },
  {
    id: "retro-arsenal-01-02",
    name: "Arsenal 2001/02",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-arsenal-01-02.jpg",
    badge: null,
  },
  {
    id: "retro-arsenal-04-05",
    name: "Arsenal 2004/05",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-arsenal-04-05.jpg",
    badge: null,
  },
  {
    id: "retro-aston-villa-1988",
    name: "Aston Villa 1988",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-aston-villa-1988.jpg",
    badge: null,
  },
  {
    id: "retro-atletico-paranaense",
    name: "Atlético Paranaense",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-atletico-paranaense.jpg",
    badge: null,
  },
  {
    id: "retro-barcelona-10-11",
    name: "Barcelona 2010/11",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-barcelona-10-11.jpg",
    badge: null,
  },
  {
    id: "retro-barcelona-14-15",
    name: "Barcelona 2014/15",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-barcelona-14-15.jpg",
    badge: null,
  },
  {
    id: "retro-boca-juniors-2001",
    name: "Boca Juniors 2001",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-boca-juniors-2001.jpg",
    badge: null,
  },
  {
    id: "retro-brasil-1958",
    name: "Brasil 1958",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-brasil-1958.jpg",
    badge: null,
  },
  {
    id: "retro-brasil-1971",
    name: "Brasil 1971",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-brasil-1971.jpg",
    badge: null,
  },
  {
    id: "retro-brasil-2002r",
    name: "Brasil 2002",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-brasil-2002r.jpg",
    badge: null,
  },
  {
    id: "retro-brasil-2006",
    name: "Brasil 2006",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-brasil-2006.jpg",
    badge: null,
  },
  {
    id: "retro-brasil-1994",
    name: "Brasil 1994",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-brasil-1994.jpg",
    badge: null,
  },
  {
    id: "retro-brasil-goleiro-1998",
    name: "Brasil 1998 — Goleiro",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-brasil-goleiro-1998.jpg",
    badge: null,
  },
  {
    id: "retro-corinthians-99-00",
    name: "Corinthians 1999/00",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-corinthians-99-00.jpg",
    badge: null,
  },
  {
    id: "retro-espanha-2010-casa",
    name: "Espanha 2010 — Casa",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-espanha-2010-casa.jpg",
    badge: null,
  },
  {
    id: "retro-espanha-2010-fora",
    name: "Espanha 2010 — Fora",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-espanha-2010-fora.jpg",
    badge: null,
  },
  {
    id: "retro-fenerbahce-08-09",
    name: "Fenerbahçe 2008/09",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-fenerbahce-08-09.jpg",
    badge: null,
  },
  {
    id: "retro-fiorentina-97-98",
    name: "Fiorentina 1997/98",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-fiorentina-97-98.jpg",
    badge: null,
  },
  {
    id: "retro-flamengo-1981",
    name: "Flamengo 1981",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-flamengo-1981.jpg",
    badge: null,
  },
  {
    id: "retro-flamengo-2019",
    name: "Flamengo 2019",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-flamengo-2019.jpg",
    badge: null,
  },
  {
    id: "retro-fluminense-2010",
    name: "Fluminense 2010",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-fluminense-2010.jpg",
    badge: null,
  },
  {
    id: "retro-franca-1998",
    name: "França 1998",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-franca-1998.jpg",
    badge: null,
  },
  {
    id: "retro-franca-2018",
    name: "França 2018",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-franca-2018.jpg",
    badge: null,
  },
  {
    id: "retro-getafe-09-10",
    name: "Getafe 2009/10",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-getafe-09-10.jpg",
    badge: null,
  },
  {
    id: "retro-gremio-2000",
    name: "Grêmio 2000",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-gremio-2000.jpg",
    badge: null,
  },
  {
    id: "retro-gremio-97-98",
    name: "Grêmio 1997/98",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-gremio-97-98.jpg",
    badge: null,
  },
  {
    id: "retro-holanda-1988",
    name: "Holanda 1988",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-holanda-1988.jpg",
    badge: null,
  },
  {
    id: "retro-holanda-1988-fora",
    name: "Holanda 1988 — Fora",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-holanda-1988-fora.jpg",
    badge: null,
  },
  {
    id: "retro-holanda-78-80",
    name: "Holanda 1978/80",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-holanda-78-80.jpg",
    badge: null,
  },
  {
    id: "retro-inter-milao-1998r",
    name: "Inter de Milão 1998",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-inter-milao-1998r.jpg",
    badge: null,
  },
  {
    id: "retro-italia-2004",
    name: "Itália 2004",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-italia-2004.jpg",
    badge: null,
  },
  {
    id: "retro-japao-2006r",
    name: "Japão 2006",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-japao-2006r.jpg",
    badge: null,
  },
  {
    id: "retro-japao-2014",
    name: "Japão 2014",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-japao-2014.jpg",
    badge: null,
  },
  {
    id: "retro-leganes-98-00",
    name: "Leganés 1998/00",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-leganes-98-00.jpg",
    badge: null,
  },
  {
    id: "retro-man-city-11-12",
    name: "Manchester City 2011/12",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-man-city-11-12.jpg",
    badge: null,
  },
  {
    id: "retro-man-city-13-14",
    name: "Manchester City 2013/14",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-man-city-13-14.jpg",
    badge: null,
  },
  {
    id: "retro-man-city-22-23",
    name: "Manchester City 2022/23",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-man-city-22-23.jpg",
    badge: null,
  },
  {
    id: "retro-man-city-81-82",
    name: "Manchester City 1981/82",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-man-city-81-82.jpg",
    badge: null,
  },
  {
    id: "retro-milan-06-07r",
    name: "Milan 2006/07 — Casa",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-milan-06-07r.jpg",
    badge: null,
  },
  {
    id: "retro-porto-95-96",
    name: "Porto 1995/96",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-porto-95-96.jpg",
    badge: null,
  },
  {
    id: "retro-psg-00-01",
    name: "PSG 2000/01",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-psg-00-01.jpg",
    badge: null,
  },
  {
    id: "retro-psg-17-18",
    name: "PSG 2017/18",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-psg-17-18.jpg",
    badge: null,
  },
  {
    id: "retro-psg-94-95",
    name: "PSG 1994/95",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-psg-94-95.jpg",
    badge: null,
  },
  {
    id: "retro-psg-95-96",
    name: "PSG 1995/96",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-psg-95-96.jpg",
    badge: null,
  },
  {
    id: "retro-real-madrid-07-08",
    name: "Real Madrid 2007/08",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-real-madrid-07-08.jpg",
    badge: null,
  },
  {
    id: "retro-real-madrid-11-12",
    name: "Real Madrid 2011/12",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-real-madrid-11-12.jpg",
    badge: null,
  },
  {
    id: "retro-real-madrid-16-17",
    name: "Real Madrid 2016/17",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-real-madrid-16-17.jpg",
    badge: null,
  },
  {
    id: "retro-sport-recife-2016",
    name: "Sport Recife 2016",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-sport-recife-2016.jpg",
    badge: null,
  },
  {
    id: "retro-sao-paulo-1993",
    name: "São Paulo 1993",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-sao-paulo-1993.jpg",
    badge: null,
  },
  {
    id: "retro-sao-paulo-2007",
    name: "São Paulo 2007",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-sao-paulo-2007.jpg",
    badge: null,
  },
  {
    id: "retro-valencia-95-96",
    name: "Valencia 1995/96",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-valencia-95-96.jpg",
    badge: null,
  },
  {
    id: "retro-vasco-1988",
    name: "Vasco 1988",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-vasco-1988.jpg",
    badge: null,
  },
  {
    id: "retro-vasco-1997",
    name: "Vasco 1997",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-vasco-1997.jpg",
    badge: null,
  },
  {
    id: "retro-vasco-2000",
    name: "Vasco 2000",
    category: "Retrô",
    price: 200,
    image: "fotos/retro-vasco-2000.jpg",
    badge: null,
  },
];
